version: "3.9"
services:
  chatgpt-next-web:
    # profiles: ["no-proxy"]
    container_name: MedImind
    image: chatgpt-web:v3
    pull_policy: never
    volumes:
      - ./.git:/app/.git
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - OPENAI_API_KEY=${OPENAI_API_KEY}
        - OPENAI_API_KEY_COURSE=${OPENAI_API_KEY_COURSE}
        - GOOGLE_API_KEY=$GOOGLE_API_KEY
        - CODE=$CODE
        - BASE_URL=${BASE_URL}
        - OPENAI_ORG_ID=$OPENAI_ORG_ID
        - HIDE_USER_API_KEY=$HIDE_USER_API_KEY
        - DISABLE_GPT4=$DISABLE_GPT4
        - ENABLE_BALANCE_QUERY=$ENABLE_BALANCE_QUERY
        - DISABLE_FAST_LINK=$DISABLE_FAST_LINK
        - OPENAI_SB=$OPENAI_SB
        - NEXT_PUBLIC_ENV=local
        - NEXT_PUBLIC_BACKEND_DOMAIN_URL=${NEXT_PUBLIC_BACKEND_DOMAIN_URL}
        - NEXT_PUBLIC_BACKEND_URL=${NEXT_PUBLIC_BACKEND_URL}
        - NEXT_PUBLIC_SUPABASE_URL=${NEXT_PUBLIC_SUPABASE_URL}
        - NEXT_PUBLIC_SUPABASE_ANON_KEY=${NEXT_PUBLIC_SUPABASE_ANON_KEY}
        - SUPABASE_URL=${SUPABASE_URL}
    restart: always
    ports:
      - 3002:3002

  # chatgpt-next-web-proxy:
  #   profiles: ["proxy"]
  #   container_name: MedImind-proxy
  #   image: chatgpt-web:git
  #   ports:
  #     - 3000:3000
  #   environment:
  #     - OPENAI_API_KEY=$OPENAI_API_KEY
  #     - GOOGLE_API_KEY=$GOOGLE_API_KEY
  #     - CODE=$CODE
  #     - PROXY_URL=$PROXY_URL
  #     - BASE_URL=$BASE_URL
  #     - OPENAI_ORG_ID=$OPENAI_ORG_ID
  #     - HIDE_USER_API_KEY=$HIDE_USER_API_KEY
  #     - DISABLE_GPT4=$DISABLE_GPT4
  #     - ENABLE_BALANCE_QUERY=$ENABLE_BALANCE_QUERY
  #     - DISABLE_FAST_LINK=$DISABLE_FAST_LINK
  #     - OPENAI_SB=$OPENAI_SB
  #     - NEXT_PUBLIC_ENV=local
  #     - NEXT_PUBLIC_BACKEND_URL=${NEXT_PUBLIC_BACKEND_URL}
  #     - NEXT_PUBLIC_SUPABASE_URL=${NEXT_PUBLIC_SUPABASE_URL}
  #     - NEXT_PUBLIC_SUPABASE_ANON_KEY=${NEXT_PUBLIC_SUPABASE_ANON_KEY}
